# Generated by Django 3.2.8 on 2021-10-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musicapp', '0002_auto_20211013_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='updated',
            field=models.DateTimeField(max_length=10000),
        ),
    ]
