# Generated by Django 3.2.8 on 2021-10-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musicapp', '0003_alter_shows_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='venue',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
