# Generated by Django 3.2.8 on 2021-10-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musicapp', '0004_alter_shows_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
