# Generated by Django 3.2.8 on 2021-10-13 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Musicapp', '0005_alter_shows_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shows',
            name='updated',
        ),
    ]
