# Generated by Django 3.2.8 on 2021-10-13 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Musicapp', '0007_shows_updated'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shows',
            new_name='Show',
        ),
    ]
