# Generated by Django 3.2.8 on 2021-10-18 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Musicapp', '0013_youtube2nd'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YouTube2nd',
            new_name='YouTubesecond',
        ),
    ]
