# Generated by Django 3.2.8 on 2021-10-19 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Musicapp', '0014_rename_youtube2nd_youtubesecond'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YouTubesecond',
        ),
    ]
