# Generated by Django 3.2.8 on 2021-10-19 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Musicapp', '0016_youtubesecond'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtubesecond',
            old_name='updated',
            new_name='update',
        ),
    ]
