# Generated by Django 3.2.8 on 2021-10-19 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Musicapp', '0018_rename_videoid_youtubesecond_vidid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtubesecond',
            old_name='update',
            new_name='updated',
        ),
    ]
