# Generated by Django 3.2.8 on 2021-10-21 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Musicapp', '0022_auto_20211021_0226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
